# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anjar Febrianto
email: hello@namilabs.com
description: > # this means to ignore newlines until "baseurl:"
  Namilabs.com, we  build your dream come true.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://namilabs.com" # the base hostname & protocol for your site
twitter: namilabscom
github:  namilabs
permalink: journal/:year/:month/:day/:hour:minute:second-:title.html
# Build settings
markdown: kramdown
gem:
    - jekyll-sitemap
